server:
  port:
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quanlytaichinh?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
api:
  prefix: api/v1
jwt:
  expiration: 2592000
  secretKey: OJd3+enSUenPVIIVVRHLo55UKObjfWXF1mi1lzby2/A=
